apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sysdig
  namespace: sysdig-agent
spec:
  interval: 30m
  chart:
    spec:
      chart: sysdig-deploy # no alias, just the chart name
      version: "1.40.0"
      sourceRef:
        kind: HelmRepository
        name: sysdig
      interval: 10m
      values:




